#
# This file is part of Nya Client.
#
# Nya Client is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# Nya Client is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with Nya Client. If not, see <https://www.gnu.org/licenses/>.
#

#
#  This file is part of Nya Client.
#
# Nya Client is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# Nya Client is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with Nya Client. If not, see <https://www.gnu.org/licenses/>.
#

version=1.0.0
group=net.nyaclient
java_version=21

mod_name=Nya Client
mod_author=Angel
mod_id=nyaclient
license=GPL-3.0
credits=See CREDITS.md
description=A free and open source alternative to clients like Lunar/Badlion.

fabric_minecraft_version=1.20.6
fabric_version=0.99.0+1.20.6
fabric_loader_version=0.15.11
fabric_loom_version=1.16-SNAPSHOT
fabric_api_version=0.100.8+1.20.6

legacy_fabric_yarn_build=604
legacy_fabric_loader_version=0.19.3
legacy_fabric_loom_version=1.15-SNAPSHOT
legacy_fabric_api_version=1.13.5+1.8.9

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false