import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import net.fabricmc.loom.task.RunGameTask
import org.gradle.internal.os.OperatingSystem

plugins {
	id "net.fabricmc.fabric-loom-remap" version "${loom_version}"
	id "legacy-looming" version "${loom_version}"
	id "maven-publish"
	id "com.gradleup.shadow" version "8.3.0"
}

tasks.named("shadowJar", ShadowJar) {
	configurations = [project.configurations.shadow]
	archiveClassifier.set("shadow")
}

remapJar {
	dependsOn shadowJar
	inputFile.set(shadowJar.archiveFile)
}

ext {
	lwjglVersion = "3.3.2"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
	maven { url = 'https://jitpack.io' }
}

loom {

}

legacyLooming {

}

//project.ext.lwjglVersion = project.findProperty('lwjgl_version')

def currentOs = OperatingSystem.current()

if (currentOs.isLinux()) {
	project.ext.lwjglNatives = "natives-linux"
	def osArch = System.getProperty("os.arch")
	if (osArch.startsWith("arm") || osArch.startsWith("aarch64")) {
		project.ext.lwjglNatives += osArch.contains("64") || osArch.startsWith("armv8") ? "-arm64" : "-arm32"
	} else if (osArch.startsWith("ppc")) {
		project.ext.lwjglNatives += "-ppc64le"
	} else if (osArch.startsWith("riscv")) {
		project.ext.lwjglNatives += "-riscv64"
	}
} else if (currentOs.isMacOsX()) {
	project.ext.lwjglNatives = "natives-macos"
	def osArch = System.getProperty("os.arch")
	if (osArch.startsWith("aarch64")) {
		project.ext.lwjglNatives += "-arm64"
	}
} else if (currentOs.isWindows()) {
	def osArch = System.getProperty("os.arch")
	project.ext.lwjglNatives = osArch.contains("64")
			? "natives-windows${osArch.startsWith("aarch64") ? "-arm64" : ""}"
			: "natives-windows-x86"
}

dependencies {
	minecraft "com.mojang:minecraft:1.8.9"
	mappings "net.legacyfabric:yarn:1.8.9+build.604:v2"
	modImplementation "net.fabricmc:fabric-loader:0.19.3"


	modImplementation "net.legacyfabric.legacy-fabric-api:legacy-fabric-api:1.13.5+1.8.9"
	// implementation('com.google.code.gson:gson:2.8.9')

	compileOnly "org.projectlombok:lombok:1.18.46"
	annotationProcessor "org.projectlombok:lombok:1.18.46"

	testCompileOnly "org.projectlombok:lombok:1.18.46"
	testAnnotationProcessor "org.projectlombok:lombok:1.18.46"

	implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

	modImplementation "io.waterwave.Legacy-LWJGL3:lwjgl:$lwjglVersion-5"
	modImplementation "io.waterwave.Legacy-LWJGL3:lwjgl-stb:$lwjglVersion-5"
	modImplementation "io.waterwave.Legacy-LWJGL3:lwjgl-nanovg:$lwjglVersion-5"

	include "io.waterwave.Legacy-LWJGL3:lwjgl:$lwjglVersion-5"
	include "io.waterwave.Legacy-LWJGL3:lwjgl-stb:$lwjglVersion-5"
	include "io.waterwave.Legacy-LWJGL3:lwjgl-nanovg:$lwjglVersion-5"

	runtimeOnly "org.lwjgl:lwjgl:$lwjglVersion:$lwjglNatives"
	runtimeOnly "org.lwjgl:lwjgl-nanovg:$lwjglVersion:$lwjglNatives"
	runtimeOnly "org.lwjgl:lwjgl-stb:$lwjglVersion:$lwjglNatives"

	modRuntimeOnly "org.lwjgl:lwjgl:$lwjglVersion:$lwjglNatives"
	modRuntimeOnly "org.lwjgl:lwjgl-nanovg:$lwjglVersion:$lwjglNatives"
	modRuntimeOnly "org.lwjgl:lwjgl-stb:$lwjglVersion:$lwjglNatives"

	include "org.lwjgl:lwjgl:$lwjglVersion:$lwjglNatives"
	include "org.lwjgl:lwjgl-nanovg:$lwjglVersion:$lwjglNatives"
	include "org.lwjgl:lwjgl-stb:$lwjglVersion:$lwjglNatives"

	// modImplementation(legacy.apiModule("legacy-fabric-item-groups-v1", project.fabric_version))
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"

	if (JavaVersion.current().isJava9Compatible()) {
		it.options.release = 8
	}
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_1_8
	targetCompatibility = JavaVersion.VERSION_1_8
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
	}
}

tasks.register("extractLwjglNatives") {
	doLast {
		def nativesDir = file("${buildDir}/lwjgl-natives")
		nativesDir.mkdirs()

		configurations.runtimeClasspath.each { file ->
			if (file.name.contains("natives") && file.name.contains("lwjgl")) {
				copy {
					from zipTree(file)
					into nativesDir
					include "*.so", "*.dll", "*.dylib"
				}
			}
		}
	}
}

tasks.withType(RunGameTask).configureEach {
	dependsOn extractLwjglNatives
	jvmArgs "-Djava.library.path=${buildDir}/lwjgl-natives", "-Dorg.lwjgl.librarypath=${buildDir}/lwjgl-natives"
}